export const themes = {
  default: {
    fontColor: '',
    primary: '#2A2D34',
    primaryVariant: '',
    secondary: '',
    secondaryVariant: '',
    error: '',
    warning: '',
    success: '',
    background: '#fff',
    surface: '',
    textOpacity: '',
    borderOpacity: '',
    iconOpacity: '',
    iconColor: '',
  },
  green: {
    primary: '',
    primaryVariant: '',
    secondary: '',
    secondaryVariant: '',
    error: '',
    warning: '',
    success: '',
    background: '',
    surface: '',
    textOpacity: '',
    borderOpacity: '',
    iconOpacity: '',
  },
  dark: {
    primary: '',
    primaryVariant: '',
    secondary: '',
    secondaryVariant: '',
    error: '',
    warning: '',
    success: '',
    background: '#000',
    surface: '',
    textOpacity: '',
    borderOpacity: '',
    iconOpacity: '',
  },
  colors: {
    powderWhite: '#FFFDF9',
    persianGreen: '#06B49A',
    lightBlue: '#AFDBD2',
    onyx: '#36313D',
    carolinaBlue: '#009DDC',
    orangePantone: '#F26430',
    nightPurple: '#6761A8',
    greenCyan: '#009B72',
    lava: '#C42021',
  },
  fonts: ['sans-serif', 'Roboto'],
  fontSizes: {
    small: '1em',
    medium: '2em',
    large: '3em',
  },
}
